### ISSUE TITLE
[BUG] Can't add new dependencies

### ISSUE THREAD

**Issue by neeeekitos** [pancakeswap/pancake-frontend#10046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

When I add a new dependency to the project and run it, I encounter a 'Wagmi' error:

```
web:dev:  ⚠ ../../node_modules/.pnpm/debug@4.3.4_supports-color@9.4.0/node_modules/debug/src/node.js
web:dev: Module not found: ESM packages (supports-color) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
web:dev:
web:dev: Import trace for requested module:
web:dev: ../../node_modules/.pnpm/debug@4.3.4_supports-color@9.4.0/node_modules/debug/src/node.js
web:dev: ../../node_modules/.pnpm/debug@4.3.4_supports-color@9.4.0/node_modules/debug/src/index.js
web:dev: ../../packages/smart-router/dist/evm.mjs
web:dev: ./src/config/constants/exchange.ts
web:dev: ./src/state/lists/updater.ts
web:dev: ./src/index.tsx
web:dev: bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
web:dev: redux-persist failed to create sync storage. falling back to noop storage.
web:dev: Datadog Browser SDK: Client Token is not configured, we will not send any data.
web:dev: WagmiProviderNotFoundError: `useConfig` must be used within `WagmiProvider`.
web:dev:
web:dev: Docs: https://wagmi.sh/react/api/WagmiProvider.html
web:dev: Version: wagmi@2.9.8
web:dev:     at useConfig (webpack-internal:///../../node_modules/.pnpm/wagmi@2.9.8_@tanstack+query-core@5.29.0_@tanstack+react-query@5.29.2_react@18.2.0__@types+rea_4ax5m5mwwkgjsoz6tphd535qlm/node_modules/wagmi/dist/esm/hooks/useConfig.js:19:15)
web:dev:     at useBlock (webpack-internal:///../../node_modules/.pnpm/wagmi@2.9.8_@tanstack+query-core@5.29.0_@tanstack+react-query@5.29.2_react@18.2.0__@types+rea_4ax5m5mwwkgjsoz6tphd535qlm/node_modules/wagmi/dist/esm/hooks/useBlock.js:24:76)
web:dev:     at useWatchBlock (webpack-internal:///../../packages/wagmi/dist/index.mjs:79:83)
web:dev:     at usePollBlockNumber (webpack-internal:///./src/state/block/hooks.ts:25:70)
web:dev:     at GlobalHooks (webpack-internal:///./src/pages/_app.tsx:120:75)
web:dev:     at renderWithHooks (/Users/nikita/Projects/cedelabs/test/pancake-frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
```

### Expected Behavior

Should run the project without any error.

### Steps To Reproduce

1. Install a random dependency from npm
2. Run `pnpm dev`
3. Notice "WagmiProviderNotFoundError: `useConfig` must be used within `WagmiProvider`." error in `web` app.

### Environment

```markdown
- Device: MacBook Pro
- OS: 14.5 (23F79)
- Browser: -
- Wallet: -
```

**Comment by chefjackson** [comment]
Hi please make sure you're using pnpm version `8.x`

**Comment by chefjackson** [comment]
Hi catalogs are added to the workspace. Should be good now. Please upgrade the pnpm version to `9.5.0` and try reinstall
