### ISSUE TITLE
[BUG] <title>Unexpected token

### ISSUE THREAD

**Issue by AndriKusumaBhakti** [pancakeswap/pancake-frontend#1914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

/home/dsi/Downloads/rainbow/pancake-frontend/node_modules/p-limit/index.js:29
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dsi/Downloads/rainbow/pancake-frontend/node_modules/terser-webpack-plugin/dist/index.js:24:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected Behavior

/home/dsi/Downloads/rainbow/pancake-frontend/node_modules/p-limit/index.js:29
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dsi/Downloads/rainbow/pancake-frontend/node_modules/terser-webpack-plugin/dist/index.js:24:38)
error Command failed with exit code 1.

### Steps To Reproduce

Unexpected token

### Environment

```markdown
- Device: Linux
- OS: 16:04
- Browser:Chrome
```

### Anything else?

/home/dsi/Downloads/rainbow/pancake-frontend/node_modules/p-limit/index.js:29
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dsi/Downloads/rainbow/pancake-frontend/node_modules/terser-webpack-plugin/dist/index.js:24:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hachiojidev** [comment]
@AndriKusumaBhakti You will have to provide some more information. What version of Node are you using? What were you trying to do?

**Comment by ShaunLWM** [comment]
Update your Node version.
https://github.com/googleapis/nodejs-storage/issues/1223#issuecomment-648427815
