### ISSUE TITLE
[BUG] <Stake Error In Pool>

### ISSUE THREAD

**Issue by HuzaifaKhanDeveloper** [pancakeswap/pancake-frontend#3784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Syrup Pools

### Current Behavior

The 1st Error Is 
![image](https://user-images.githubusercontent.com/103213190/165355871-73c24899-b987-4ba6-a94a-b7e1fdd35744.png)

Access to fetch at 'https://nodes.pancakeswap.com/' from origin 'http://192.168.1.10:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Expected Behavior

The 2nd Error Is 
![image](https://user-images.githubusercontent.com/103213190/165355816-8774b850-9185-4cb9-a66b-077340a18999.png)

next-dev.js?3515:25 Warning: Received `false` for a non-boolean attribute `scrolling`.

If you want to write it to the DOM, pass a string instead: scrolling="false" or scrolling={value.toString()}.

If you used to conditionally omit it with scrolling={condition && value}, pass scrolling={condition ? value : undefined} instead.
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
    at Dropdown (webpack-internal:///./packages/uikit/src/components/Dropdown/Dropdown.tsx:103:24)
    at LangSelector (webpack-internal:///./packages/uikit/src/components/LangSelector/LangSelector.tsx:20:29)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
    at nav
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
    at Menu (webpack-internal:///./packages/uikit/src/widgets/Menu/Menu.tsx:163:32)
    at Menu (webpack-internal:///./src/components/Menu/index.tsx:115:73)
    at App (webpack-internal:///./src/pages/_app.tsx:275:27)
    at PersistGate (webpack-internal:///./node_modules/redux-persist/es/integration/react.js:39:5)
    at Blocklist (webpack-internal:///./src/index.tsx:46:26)
    at ModalProvider (webpack-internal:///./packages/uikit/src/widgets/Modal/ModalContext.tsx:97:26)
    at SWRConfig$1 (webpack-internal:///./node_modules/swr/dist/index.mjs:504:23)
    at LanguageProvider (webpack-internal:///./src/contexts/Localization/Provider.tsx:97:26)
    at Fe (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:17360)
    at StyledThemeProvider (webpack-internal:///./src/Providers.tsx:57:78)
    at u (webpack-internal:///./node_modules/next-themes/dist/index.modern.js:11:246)
    at ToastsProvider (webpack-internal:///./src/contexts/ToastsContext/Provider.tsx:46:27)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at Web3ReactProvider (webpack-internal:///./node_modules/@web3-react/core/dist/core.esm.js:553:27)
    at Providers (webpack-internal:///./src/Providers.tsx:73:26)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:123:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)

### Steps To Reproduce

1. I Just Download Your Open Source
2, I Just Install React In Repostory
3. I Run It To Local Host
4. I Check Pool But There Was An Error

Note  :- My Public URL Is Online :- http://192.168.1.10:3000/
But It Online Only 9:30 to 2:00 (GMT+5)

### Environment

```markdown
- Device: Lenovo
- OS: Windows
- Browser: Chrome
- Wallet: 0xa340f783AA730B41d59Ba7e1E3A92a1D4f08D2BA
```

### Anything else?

Please Help Me

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/
